port:               4004
title:              wildthinks
email:              goldfishandrobin@gmail.com
description:        interactive mathematics explorations
author:             Heidi Dixon
url:                "https://wildthinkslaboratory.github.io"

# Social Profiles
twitter_username:   wildthinksLab
github_username:    wildthinkslaboratory
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: wildthinkslaboratory-github-io


lessons :
  rectangle: 
    - url: /pages/rectangle1/
      name: one
    - url: /pages/rectangle2/
      name: two
    - url: /pages/rectangle3/
      name: three
    - url: /pages/rectangle4/
      name: four
    - url: /pages/rectangle5/
      name: five
    - url: /pages/rectangleAUC/
      name: six
    - url: /pages/work/
      name: seven
    - url: /pages/balance/
      name: eight
    - url: /pages/rectanglePoints/
      name: nine

  secant:
    - url: /pages/secant1/
      name: one
    - url: /pages/secant2/
      name: two
    - url: /pages/secant3/
      name: three
    - url: /pages/secant4/
      name: four
    - url: /pages/secant5/
      name: five
    - url: /pages/secant6/
      name: six
    - url: /pages/secant7/
      name: seven
    - url: /pages/secantPoints/
      name: eight

  secant_rectangle: 
    - url: /pages/prelude/
      name: one
    - url: /pages/rectangleMatch/
      name: two
    - url: /pages/secantMatch/
      name: three
    - url: /pages/secantRectangle1/
      name: four
    - url: /pages/secantRectangle2/
      name: five
    - url: /pages/shadowRectCurve/
      name: six
    - url: /pages/shadowSecantCurve/
      name: seven
  
  derivative: 
    - url: /pages/symbols1/
      name: one
    - url: /pages/derivative0/
      name: two
    - url: /pages/derivative1/
      name: three
    - url: /pages/derivative2/
      name: four
    - url: /pages/derivative3/
      name: five 
    - url: /pages/derivative4/
      name: six 
    - url: /pages/derivative5/
      name: seven
      
  negative_binary:
    - url: /pages/NegaBinary1/
      name: one
    - url: /pages/NegaBinary2/
      name: two
    - url: /pages/NegaBinary3/
      name: three
    - url: /pages/NegaBinary4/
      name: four
    - url: /pages/NegaBinary5/
      name: five

  limit:
    - url: /pages/limit1/
      name: one
    - url: /pages/limit3/
      name: two
    - url: /pages/limit2/
      name: three
    - url: /pages/limit4/
      name: four
    - url: /pages/limit5/
      name: five
    - url: /pages/limitSummary1/
      name: six

  more_limits:
    - url: /pages/limitDEIntro/
      name: one
    - url: /pages/limitDE1/
      name: two
    - url: /pages/limitDE2/
      name: three
    - url: /pages/limitDE3/
      name: four
    - url: /pages/limitDE4/
      name: five
            
# Build settings
# remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll # mmistakes/minimal-mistakes
theme: jekyll-theme-clean-blog
markdown:           kramdown
markdown_ext:       markdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

excerpt_separator: <!--more-->

include:
  - posts
  - pages
exclude:
  - Gemfile
  - Gemfile.lock
  - dist
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _hide/
  - README.md
  - targets/mm/
  - targets/legacy/
  - "*.sh"




collections:
  posts:
    output: true
    permalink: /posts/:title/
  rawposts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /pages/:title/
  rawpages:
    output: true
    permalink: /pages/:title
  # about:
  #   output: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "rawposts"
      type: "posts"
    values:
      layout: "raw"
  - scope:
      path: "rawpages"
      type: "pages"
    values:
      layout: "raw"
